name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: List files before install
        run: ls -la

      - name: Install Dependencies
        run: |
          npm install
          npm install -g gh-pages --save-dev

      - name: List files after install
        run: ls -la

      - name: Build
        env:
          CI: false
        run: npm run build

      - name: List build directory
        run: |
          echo "Build directory contents:"
          ls -la build/

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Deploy
        run: |
          echo "Starting deployment..."
          cp public/CNAME build/
          npx gh-pages -d build -t true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
